language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
    - libglpk-dev
    
r_packages:
  - stringr
  - magrittr
  - Rglpk

r_github_packages:
  - hadley/testthat
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library(covr); codecov()'
