language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
    - libglpk-dev

r_github_packages:
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  - dirkschumacher/ompr
  - dirkschumacher/ompr.roi

r_packages:
  - slam

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'

env:
  - LINTR_COMMENT_BOT=true
