language: r
r:
  - release
  - devel
  - oldrel
sudo: false
cache: packages

r_github_packages:
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'

env:
  - LINTR_COMMENT_BOT=false
